[project]
name = "aiml-track"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harsh Singh", email = "harsh_singh90@yahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.scripts]
aiml-track = "aiml_track:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
