#!/usr/bin/env python3
"""
Sync aiml-dashboard.html from aiml-dashboard-state.json.

The dashboard is a single self-contained HTML file, so it cannot fetch() the
JSON when opened from disk (file:// blocks it). Instead the state is embedded
as `const STATE = {...};` and regenerated by this script.

Run this after every session, or the dashboard silently shows stale data:

    uv run python sync-dashboard.py
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
STATE_FILE = ROOT / "aiml-dashboard-state.json"
HTML_FILE = ROOT / "aiml-dashboard.html"

# Literal strings baked into the markup that the STATE block does not control.
#
# EMPTIED 14 Aug 2026. This list was a landmine: it rewrote markup toward values that were
# themselves stale (e.g. it would have re-inserted "Friday 7 August 2026" as Day 1, which the
# 10 Aug restart replaced with 11 August). Patching literal strings after the fact is how the
# dashboard drifted from the plan three separate times.
#
# The dashboard now derives dates, session counts, exam formats and pass gates from STATE at
# render time, so there is nothing left for this list to fix. Keep it empty. If you find
# yourself wanting to add an entry here, the correct fix is to make the markup read from STATE
# instead.
TEXT_FIXES = []


def main() -> int:
    if not STATE_FILE.exists() or not HTML_FILE.exists():
        print("error: run this from the aiml-track folder", file=sys.stderr)
        return 1

    state = json.loads(STATE_FILE.read_text())
    html = HTML_FILE.read_text()

    block = "const STATE = " + json.dumps(state, indent=2, ensure_ascii=False) + ";"
    new_html, n = re.subn(
        r"const STATE = \{.*?^\};",
        lambda _: block,
        html,
        count=1,
        flags=re.DOTALL | re.MULTILINE,
    )
    if n != 1:
        print("error: could not locate the `const STATE = {...};` block", file=sys.stderr)
        return 1

    fixed = []
    for old, new in TEXT_FIXES:
        if old in new_html:
            new_html = new_html.replace(old, new)
            fixed.append(new)

    HTML_FILE.write_text(new_html)

    axes = ", ".join(f"{k} {v['current']}" for k, v in state["skillAxes"].items())
    meta = state["meta"]
    print("dashboard synced")
    print(f"  streak      {state['streak']['current']}")
    print(f"  quizzes     {len(state['quizHistory'])}  exams {len(state['examHistory'])}")
    print(f"  week/phase  {meta.get('currentWeek')} / {meta.get('currentPhase')}")
    print(f"  axes        {axes}")
    if fixed:
        print(f"  text fixes  {len(fixed)} applied")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
